version: '3.7'

services:
  api:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgresql
    ports:
      - "3000:3000"

  postgresql:
    image: postgres:12.4-alpine
    env_file: .env
    expose:
      - "5432"